apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: app-deployment
spec:
  selector:
    matchLabels:
      app: finapp
  replicas: 2
  template:
    metadata:
      labels:
        app: finapp
    spec:
      containers:
      - name: finapp
        image: finapp:latest
        ports:
        - containerPort: 8080
